module.exports = {
  OK_STATUS_CODE: 200,
  CREATED_STATUS_CODE: 201,
  BAD_REQUEST_STATUS_CODE: 400,
  UNAUTHORIZED_STATUS_CODE: 401,
  NOT_FOUND_STATUS_CODE: 404,
  CONFLICT_STATUS_CODE: 409,
  INTERNAL_SERVER_ERROR: 500,
};
